### ISSUE TITLE
Differences between relations available on Wikidata and the LOTUS web interface

### ISSUE THREAD

**Issue by maximeDelmas** [mSorok/NaturalProductsOnline#108]
Hello,

I may have noticed some inconsistencies between the data available by SPARQL request on Wikidata and those available on the LOTUS web interface, which I understood as a mirror of what's in Wikidata.

For instance,  N(6)-(1,2-dicarboxyethyl)-AMP (Q2823236) in found produced by _Valsa sordida_ (Q7912606) and this relation is referenced by the publication _Phosphoproteomic and Metabolomic Profiling Uncovers the Roles of CcPmk1 in the Pathogenicity of Cytospora chrysosperma_ (https://doi.org/10.1128/SPECTRUM.00176-22). However, this relation does not seems to be available on the LOTUS interface.

Is this just an update issue ?

Thanks for your help.

**Comment by Adafede** [comment]
Hi @maximeDelmas! Sorry for not replying earlier (saw this issue by chance). This repo is probably not the right one to post the issue, we answered some analog ones in https://github.com/lotusnprod/lotus-web/issues. If you still have questions just get in touch!

**Comment by maximeDelmas** [comment]
Thx ! I will re-post the issue on the other repo.

Best,

Maxime
