### ISSUE TITLE
Introduce star system for annotation state of an entry

### ISSUE THREAD

**Issue by steinbeck** [mSorok/NaturalProductsOnline#18]
I suggest introducing a star or level system for the annotation state of an entry. 
Does it have:
- a chemical name
- a literature reference
- a species annotation
- a trusted resource (ChEBI, etc) as its origin.
Currently, this would lead to levels 1 to 5, being none of those, any one of the four, any two of the four, ..., all four. 
And this level annotation could be easily computed and used to decide which structures to present first to the user.

**Comment by mSorok** [comment]
Implemented, normally works, waiting for the annotation levels to actually compute to test
