### ISSUE TITLE
Clicking on DOI with link leads to error

### ISSUE THREAD

**Issue by steinbeck** [mSorok/NaturalProductsOnline#25]
I opened the card for CNP0426801, went to the "references" field which had nothing but the letters "DOI" with a link formatting. Clicking on this led to 

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jun 16 20:23:41 GMT 2020
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by mSorok** [comment]
Was an error of mine between the internal and external links. Now corrected
