### ISSUE TITLE
Searching by Coconut ID

### ISSUE THREAD

**Issue by kendallbyler** [mSorok/NaturalProductsOnline#37]
Searching by Coconut ID doesn't appear to work: "Your search for "CNP0253154" returned 0 natural product (detected query is a name).".

**Comment by mSorok** [comment]
Thank you for spotting this! I corrected the error. Note also, that if you use CNP ids from COCONUT may, they might not all match - I mis-exported the original coconut ids for that version. In this case, it's safer to query by Inchi key
