### ISSUE TITLE
Molecules missing in SDF

### ISSUE THREAD

**Issue by JonasSchaub** [mSorok/NaturalProductsOnline#39]
On the 17th of August, I downloaded COCONUT completely both as SDF and MongoDB dump. The latter contains 21 molecules more than the SDF (426895 vs. 426916). The CNP IDs of the 21 molecules missing in the SDF are: 

CNP0426896
CNP0426897
CNP0426898
CNP0426899
CNP0426900
CNP0426901
CNP0426902
CNP0426903
CNP0426904
CNP0426905
CNP0426906
CNP0426907
CNP0426908
CNP0426909
CNP0426910
CNP0426911
CNP0426912
CNP0426913
CNP0426914
CNP0426915
CNP0426916

They all have the cross reference remark 'This compound is not present in a currently existing database. It was retrieved from the following collection(s): piellabdata'. Does this maybe have something to do with it? Is it intentional that they are missing in the SDF? 

Sorry for bringing this up on a Friday evening. Just ignore it until Monday!

Kind regards and have a nice weekend,
Jonas

**Comment by mSorok** [comment]
It was a delay in the SDF export. I updated everything now
