### ISSUE TITLE
Empty view when clicking further from last page

### ISSUE THREAD

**Issue by michaelwenk** [mSorok/NaturalProductsOnline#43]
<img width="600" alt="Bildschirmfoto 2020-09-07 um 19 02 58" src="https://user-images.githubusercontent.com/30418272/92408345-82530780-f13d-11ea-8374-83b6bb4406cc.png">

If we are on the last page and the click further to the "next" one, then the view gets empty. (See picture above)
And the current page the selection is gone (no blue background colour). Same happens for the first page when we click back (to -1). 
One could disable those buttons for clicking forwards/backwards if the last/first page has been reached.

Would it be better to start from 1 instead of 0 ?

**Comment by mSorok** [comment]
Thank you for noticing! Fixed!
