### ISSUE TITLE
Exact mass would help mass spectrometry identification

### ISSUE THREAD

**Issue by sneumann** [mSorok/NaturalProductsOnline#52]
Hi, 
NPO includes the `molecular_weight`, but afaics not the exact monoisotopic mass. 
That would be really cool for people doing identification, and saves recalculating from the molecular formula upon database import. Is there a way to add that ? Or is that a design decision ?
Yours,
Steffen

**Comment by robertsamples** [comment]
This would be really fantastic we would like to search monoisotopic masses using the API.

**Comment by trljcl** [comment]
plus one on that

**Comment by mSorok** [comment]
Hi, 

I included the possibility of retrieving NP entries via the API based on the molecular weight in the latest release (just forgot to notify it here).
The description of how to use it is in the documentation section, I put this here for the example:

https://coconut.naturalproducts/net/api/search/molweight?minMass=800&maxMass=1000&maxHits=20

Note that you can also use only min or max.
