### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sofeaarina** [mSorok/NaturalProductsOnline#59]
is it just me? or it crashes when using advanced search of 10,000 ligands with a few other filters

**Comment by mSorok** [comment]
We are experiencing massive network shortages this week, so your problem comes from this. Please, try again, it should work slightly better now.
Otherwise, the API (as described in the documentation session) is working better as the data flux is lower.
I apologize for this inconvenience! The IT of our University is working on this issue

**Comment by sofeaarina** [comment]
> We are experiencing massive network shortages this week, so your problem comes from this. Please, try again, it should work slightly better now.
> Otherwise, the API (as described in the documentation session) is working better as the data flux is lower.
> I apologize for this inconvenience! The IT of our University is working on this issue

Hi thank you for the response, i came back to try again unfortunately it still can't process my search. i'm quite unclear with the documentation however i would really love to use this database. May i know if i download the whole dataset using mongoDB will i be able to filter the data same as the advanced search options like cp3, lipinski rule of 5 and others?

**Comment by mSorok** [comment]
Hi, I did some modifications, can you please check if it works better now?
Otherwise, I will assist you in your queries on the local COCONUT installation

**Comment by sofeaarina** [comment]
hi yes i've managed to use the advanced search option. thank you very much. Ive done my virtual screening and came back to seach the compound using coconut id but it came out error everytime i tried since morning. is it problem with the network shortages again? 
![image](https://user-images.githubusercontent.com/63838426/113487936-740b7500-94ed-11eb-899b-bae1d1041a3a.png)
