### ISSUE TITLE
Releases of SDF files need to be updates as they are 1.5 years old

### ISSUE THREAD

**Issue by steinbeck** [mSorok/NaturalProductsOnline#77]
Releases of SDF files need to be updates as they are 1.5 years old (https://coconut.naturalproducts.net/download).
Also, those files should really be compressed (zipped or gzipped)

**Comment by Sundican** [comment]
Any progress on this end?

**Comment by steinbeck** [comment]
Not yet. Our lead developer has changed jobs and various other reasons prevented any action from us less capable. But this is not forgotten :)

**Comment by Kohulan** [comment]
The new data and compressed SDF are now available
