### ISSUE TITLE
The file coconut_db.sdf can't split into small file, it only contain 2 compounds?

### ISSUE THREAD

**Issue by alongdedidi** [mSorok/NaturalProductsOnline#78]
<img width="539" alt="12" src="https://user-images.githubusercontent.com/95422898/144429902-18e4497d-8154-4fe3-a6f1-9efffd4ae334.PNG">

**Comment by steinbeck** [comment]
A bit more information is always helpful when filing an issue. :)
Where did you get this screenshot from, or better, from where did you download the coconut_db.sdf? 
I actually downloaded the coconut_db.sdf today from https://coconut.naturalproducts.net/download and it contains 406747 SDF entries (molecules).

**Comment by alongdedidi** [comment]
> 

3Q for your reply, but I truly downloaded the coconut_db.sdf today from https://coconut.naturalproducts.net/download. could you please tell me how to  split the file, or give me  a link about obabel .

**Comment by steinbeck** [comment]
Funny that you ask that :) 
I just wanted to write to you exactly this:

obabel -i sdf COCONUT_DB.sdf -o mol -O coco.mol -m

This will give you coco1.mol, coco2.mol, etc

**Comment by alongdedidi** [comment]
> Funny that you ask that :) I just wanted to write to you exactly this:
> 
> obabel -i sdf COCONUT_DB.sdf -o mol -O coco.mol -m
> 
> This will give you coco1.mol, coco2.mol, etc
> 
> But: I also noted that my download is larger: 3048817341 Dec 2 11:19 COCONUT_DB.sdf. Maybe yours was not complete? I just filed an issue today, btw, that the SDF's should be zipped.



> Funny that you ask that :) I just wanted to write to you exactly this:
> 
> obabel -i sdf COCONUT_DB.sdf -o mol -O coco.mol -m
> 
> This will give you coco1.mol, coco2.mol, etc
> 
> But: I also noted that my download is larger: 3048817341 Dec 2 11:19 COCONUT_DB.sdf. Maybe yours was not complete? I just filed an issue today, btw, that the SDF's should be zipped.

i'm sorry, i'm a student major in phytochemistry. I don't know much about chemoinformatics; I want the single file with SDF format, professor can you give me some advice ?

**Comment by steinbeck** [comment]
SDF and mol files are the same format. So if you want to split the big coconut_db.sdf into individual molecules, you need to run the command that I gave you  (obabel -i sdf COCONUT_DB.sdf -o sdf -O coco.sdf -m). Openbabel can be downloaded from http://openbabel.org/. If you have further issues, send me an email to christoph.steinbeck@uni-jena.de since the thread is no longer related to a problem with the coconut DB.

**Comment by alongdedidi** [comment]
Thank you very much professor (^_^)

**Comment by alongdedidi** [comment]
btw, professor the  3048817341 bit/1024= 2977361 kB (^_^)
