### ISSUE TITLE
MongoDB download

### ISSUE THREAD

**Issue by niclas-gr** [mSorok/NaturalProductsOnline#83]
Hi,

I've been trying to download the complete COCONUT dataset as a MongoDB dump. While the download starts and runs with at least 1 MBit/s the downloaded amount of data irregularly resets (or is at least reduced) and after some minutes the download fails.

I have attempted a download both on Google Chrome and Windows Edge. 

I'm not sure what the problem here is. Downloads from other websites work as usual.

**Comment by CS76** [comment]
Hello @niclas-gr, 
Thank you for reporting the issue. Can you give it a try again? and let us know if the issue still persists.

**Comment by niclas-gr** [comment]
Hi, 

it does work now. Thanks a lot!

**Comment by Kohulan** [comment]
@niclas-gr 
Thank you for confirming :)
