### ISSUE TITLE
Remove flourinated natural products found by Adelene

### ISSUE THREAD

**Issue by steinbeck** [mSorok/NaturalProductsOnline#89]

**Comment by adelenelai** [comment]
I found 64 CNPs forming 23 CF2 homologous series. 

There could be more fluorinated CNPs out there, but these are just those I've found so far. 
[fluorinated_cnps_to_remove_from_COCONUT.csv](https://github.com/mSorok/NaturalProductsOnline/files/8583232/fluorinated_cnps_to_remove_from_COCONUT.csv)

**Comment by Kohulan** [comment]
Removing the molecules without clear reference and annotations.
