### ISSUE TITLE
Problems with ligprep

### ISSUE THREAD

**Issue by chelardo** [mSorok/NaturalProductsOnline#94]
Hi,

I'm trying to preparate the NPs of COCONUT with ligprep to use in a Virtual Screening, but it takes so much time preparing this NPs in comparission with ZINC20 or Npatlas. So my question is there is anything that I can do for prepare the NPs in a faster way, or why it takes so much time?. In the image you can see that, when preparing the NPs of COCONUT, it use a lot of times the steps of ligprep
![índice](https://user-images.githubusercontent.com/97615801/167699633-89a1af99-d94b-44ff-a7d3-34864eb52446.jpeg)
.

**Comment by Kohulan** [comment]
Hello,

I would suggest this question you could ask the ligprep team. and it is not relevant here.

- Kohulan
